### ISSUE TITLE
aws sdk dependencies moved

### ISSUE THREAD

**Issue by clementAC** [zirkelc/aws-sigv4-fetch#14]
Hi,

AWS seems to be moving some packages to another repository, and it's making warnings during installation. Also, some messages indicate these libs are built for internal use. 

![Capture d’écran 2024-04-10 à 17 56 06](https://github.com/zirkelc/aws-sigv4-fetch/assets/10882592/9425bb92-d27d-4a46-8474-aeeb19ead179)

**Comment by zirkelc** [comment]
Thank you for reporting this. I've already updated the dependencies to the latest version (see #8), the PR is currently stuck here due to another issue: #13 

I may create a second PR just for the dependencies to release them a bit earlier. 

Regarding your second question: these libraries are not meant to be used by end users as they are a bit more complicated. But that's why I created this library, so only I have to dig through the docs and not everyone else :-D 

Translated with www.DeepL.com/Translator (free version)

**Comment by zirkelc** [comment]
Hi @clementAC 

my PR (https://github.com/smithy-lang/smithy-typescript/pull/1226) into the `smithy/*` package got merged yesterday and I just released a new version of this package with the updated dependencies.

So the newest version v3.1.0 should not print any deprecation warning any longer.
