### ISSUE TITLE
Better support for custom fetch implementations

### ISSUE THREAD

**Issue by u873838** [zirkelc/aws-sigv4-fetch#22]
The current TypeScript typing information makes it difficult to use a custom `fetch` implementation with certain libraries e.g. undici.

```typescript
import { fetch as undiciFetch } from "undici";
// ...
const signedFetch = createSignedFetcher({
    region,
    credentials,
    service: "service",
    fetch: (input, init) => {
        return undiciFetch(
            input as unknown as UndiciRequestInfo,
            init as unknown as UndiciRequestInit
        );
    },
}) as typeof undiciFetch;
```

The `createSignedFetcher` shouldn't be overly strict with what the arguments and return value the custom implementation has. It should also be generic so that the return type of `createSignedFetcher` is the same type as `SignedFetcherOptions["fetch"]`:

```typescript
const signedFetch = createSignedFetcher({
    region,
    credentials,
    service: "service",
    fetch: undiciFetch,
});
// signedFetch is typeof undiciFetch
```

**Comment by zirkelc** [comment]
Hey @u873838 thanks for bringing this to my attention. I actually didn't think there would be any type issue, because this library is using the official `fetch` types from TypeScript `DOM` lib and `unidici` implements the Fetch standard.

I'll see what I can do and will come back to you soon!

**Comment by zirkelc** [comment]
@u873838 I investigated this, here's what I found:
First of all, I didn't include any `fetch` type, but TypeScript included `lib.dom.d.ts` because I use `"lib": ["DOM"]` in the `tsconfig.json`. So I removed `DOM` and instead I added the `@types/node` types which bring their own `fetch` type. The node types actually depend on the `undici` types (see https://github.com/nodejs/undici/issues/2261):
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/719ea1fa-4cde-4e52-90dd-b0a60d0449b5">

So in theory, it should all work well with `undici`. However, when I open the `fetch` types, TypeScript still includes the `lib.dom.d.ts`:

<img width="1360" alt="image" src="https://github.com/user-attachments/assets/61e95954-4c53-4e0b-aea6-0b7c972533dc">

This issue is acknowledged in the TypeScript repo (see https://github.com/microsoft/TypeScript/issues/43990) and is probably due to a dependency using a `/// <reference lib="dom" />` directive to include the DOM types.

I tried different options like a union of `typeof globalThis.fetch | typeof undiciFetch` or building the `Request` and `Response` types myself, but without any luck. In the end I would have to build union types for each possible combination of types. This would litter the code with complex types and I would probably still miss a few types.

As a workaround, you should be able to cast the `fetch` parameter when passing it:

```ts
const signedFetch = createSignedFetcher({
  region: "us-east-1",
  credentials: {
    accessKeyId: "accessKeyId",
    secretAccessKey: "secretAccessKey",
  },
  service: "service",
  fetch: undiciFetch as typeof fetch,
});
```

By the way, which Node.js version are you using? As far as I know, since v18, `fetch` uses `undici` so you don't have to install and import it anyway.

**Comment by zirkelc** [comment]
Hey @u873838 is this still an issue for you? If so, could you help me understand why you have to use `undici` for fetching instead of using the `fetch` provided by Node.js which should be `unidici` anyway.

**Comment by zirkelc** [comment]
Glad it resolved it!
